version: '3'
services:
  mongodb-rs0-0:
    image: mongo:4.0.22-xenial
    container_name: mongodb-rs0-0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - ./mongod-rs0.conf:/etc/mongod.conf
    restart: always

  mongodb-rs0-1:
    image: mongo:4.0.22-xenial
    container_name: mongodb-rs0-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - ./mongod-rs0.conf:/etc/mongod.conf
    restart: always

  